#!/usr/bin/env php
<?php

/**
 * @desc PhpStorm.
 * @author: turpure
 * @since: 2018-03-14 16:25
 */


defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

// 一定要包含这个文件进来，完成设置的@console的别名
require(__DIR__ . '/../common/config/bootstrap.php');

//$config = require(__DIR__ . '/config/main.php');
$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/main.php'),
    require(__DIR__ . '/../common/config/main-local.php'),
    require(__DIR__ . '/../common/config/main.php'),
    require(__DIR__ . '/config/params-local.php')
);
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);